from glob import glob
from re import sub
from os.path import splitext


def main(file):
    print("[+] Processing file :- ", file)
    file_name, extension = splitext(file)
    with open(file, 'r') as te:
        te.seek(1)
        file = te.read()
        data = sub('insert into .*values', '', file).replace(';', ',')
        rem_com = sub(',$', '', data)
        with open(f'{file_name}_converted{extension}', 'w') as ou:
            ou.write('i' + rem_com)


def files():
    files = glob('*.txt')
    if len(files) == 0:
        print("[-] No files found in current directory")
        exit()
    for file in files:
        main(file)


def credit():
    global credit_text
    credit_text = """
    
               SQL EDITOR
               
     ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
    ▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
    ▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
    ▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
    ░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
    ░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
      ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
      ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
       ░           ░  ░ ░  ░  ░   ░         ░  ░ code generated by Rahul.p\n
    """
    print(credit_text)


try:
    credit()
    files()
    print("[+] file generated ")
except KeyboardInterrupt:
    print("[-] Exiting...")
except Exception as ex:
    print("[+] Error occurred ", ex)
